name: Upload Artifact

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create artifact to upload
      run: |
        echo "Hello Abhishek" > ./index.html
        cat index.html
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          ./index.html